temp_dir = "/var/tmp/virt-test"
disk_size = "100G"
base_disk_image = "./debian-12-genericcloud-amd64.qcow2"

[network]
name = "tsdbs-net"
host_ip = "10.123.123.1"

[[database]]
name = "InfluxDB"
user = "admin"
password = "admin123"
init_commands = """\
apt update && apt install -y gpg
cd $(mktemp -d)
curl --silent --location -O https://repos.influxdata.com/influxdata-archive.key
echo "943666881a1b8d9b849b74caebf02d3465d6beb716510d86a39f6c8e8dac7515  influxdata-archive.key" | sha256sum --check -
cat influxdata-archive.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdata-archive.gpg > /dev/null
echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main' | tee /etc/apt/sources.list.d/influxdata.list
apt-get update && apt install -y influxdb2
echo 'storage-cache-snapshot-write-cold-duration = "2s"' >> /etc/influxdb/config.toml
systemctl restart influxdb.service
influx setup --username $DB_USERNAME --password $DB_PASSWORD --org org --bucket bucket --retention 0 --token $DB_PASSWORD --force
"""

[[database]]
name = "TimescaleDB"
init_commands = """\
apt update && apt install -y curl ca-certificates gpg
install -d /usr/share/postgresql-common/pgdg
curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -c -s) main" | tee /etc/apt/sources.list.d/timescaledb.list
curl -fsSL https://packagecloud.io/timescale/timescaledb/gpgkey | \
    gpg --dearmor -o /etc/apt/trusted.gpg.d/timescaledb.gpg
apt update
apt install -y timescaledb-2-postgresql-17 postgresql-client postgresql-client-17
echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/17/main/pg_hba.conf
timescaledb-tune --quiet --yes --dry-run >> /etc/postgresql/17/main/postgresql.conf
systemctl restart postgresql.service
echo "CREATE EXTENSION IF NOT EXISTS timescaledb;\\dx" | sudo -u postgres psql
sed -i -e "s/#listen_addresses = 'localhost'/listen_addresses = '\\*'/g" /etc/postgresql/17/main/postgresql.conf
echo "max_connections = 500" >> /etc/postgresql/17/main/postgresql.conf
systemctl restart postgresql.service
"""

[[database]]
name = "MongoDB"
init_commands = """\
ulimit -n 64000
apt update && apt install -y gpg curl
curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
   gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
   --dearmor
echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/8.0 main" | \
    tee /etc/apt/sources.list.d/mongodb-org-8.0.list
apt update
apt install -y mongodb-org
sed -i -e 's/127\\.0\\.0\\.1/0\\.0\\.0\\.0/g' /etc/mongod.conf
systemctl enable --now mongod.service
"""

[[database]]
name = "PostgreSQL"
init_commands = """\
apt update && apt install -y curl ca-certificates
install -d /usr/share/postgresql-common/pgdg
curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
apt update
apt -y install postgresql
sed -i -e "s/#listen_addresses = 'localhost'/listen_addresses = '\\*'/g" /etc/postgresql/17/main/postgresql.conf
echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/17/main/pg_hba.conf
echo "max_connections = 500" >> /etc/postgresql/17/main/postgresql.conf
systemctl restart postgresql.service
"""
